language: c
matrix:
  fast_finish: true
  include:
    # OS X Mavericks
    - os: osx
    - compiler: clang

    # Container-based Ubuntu 12.04 LTS Server Edition 64 bit (doesn't support 32-bit includes)
    - os: linux
      sudo: false
      compiler: gcc
      env:
        - AR_SETUP="AR=gcc-ar"

    - os: linux
      sudo: false
      compiler: clang

    # Ubuntu 14.04 LTS Server Edition 64 bit
    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-arm
            - qemu-user-static
            - gcc-aarch64-linux-gnu
      compiler: aarch64-linux-gnu-gcc
      env:
        - MATRIX_EVAL="QEMU_INTERPRETER=qemu-aarch64-static && AR=gcc-ar"

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-arm
            - qemu-user-static
            - gcc-arm-linux-gnueabi
      env:
        - MATRIX_EVAL="QEMU_INTERPRETER=qemu-arm-static && CC=arm-linux-gnueabi-gcc && AR=gcc-ar"

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-ppc
            - qemu-user-static
            - gcc-powerpc-linux-gnu
      env:
        - MATRIX_EVAL="QEMU_INTERPRETER=qemu-ppc64-static && CC=powerpc-linux-gnu-gcc && AR=gcc-ar"

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-ppc
            - qemu-user-static
            - gcc-powerpc-linux-gnu
      env:
        - MATRIX_EVAL="QEMU_INTERPRETER=qemu-ppc-static && CC=powerpc-linux-gnu-gcc && AR=gcc-ar"

    - dist: trusty
      sudo: required
      env: CC=gcc

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
      env:
        - CC_SETUP="CC=gcc-4.8"
        - AR_SETUP="AR=gcc-ar"

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env:
        - CC_SETUP="CC=gcc-4.9"
        - AR_SETUP="AR=gcc-ar"

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env:
        - CC_SETUP="CC=gcc-5"
        - AR_SETUP="AR=gcc-ar-5"

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env:
        - CC_SETUP="CC=gcc-6"
        - AR_SETUP="AR=gcc-ar-6"

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env:
        - CC_SETUP="CC=gcc-7"
        - AR_SETUP="AR=gcc-ar-7"

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.5
          packages:
            - clang-3.5
      env:
        - MATRIX_EVAL="CC=clang-3.5"

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6"

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
      env:
        - MATRIX_EVAL="CC=clang-3.8"

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9"

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0"

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0"

script:
  - eval "${CC_SETUP}"
  - eval "${AR_SETUP}"
  - make
  - $QEMU_INTERPRETER ./build/density-benchmark -f
